version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./.env.local
    volumes:
      - bodmatch_db:\Users\uuaax\Develop\mysql-volumes\bodmatch
    ports:
      - 3306:3306
volumes:
  bodmatch_db:
